FROM eclipse-temurin:17-jdk-alpine

RUN apk --no-cache add curl net-tools

WORKDIR /app

ARG JAR_FILE=target/fuelman-1.0.0.jar

COPY ${JAR_FILE} app.jar

EXPOSE 8080

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /app/app.jar"]
