# this is not required, as this step is moved to dockerfile as multi stage build
- name: Maven clean package
  command:
    argv:
      - mvn
      - clean
      - package
      - -DskipTests
  when: git_result.changed
  args:
    chdir: "{{ backend_app_dir }}"
