- name: Copy backend Dockerfile
  template:
    src: Dockerfile.j2
    dest: "{{ backend_app_dir }}/Dockerfile"

- name: Copy .dockerignore
  template:
    src: dockerignore.j2
    dest: "{{ backend_app_dir }}/.dockerignore"

- name: Build backend Docker image
  community.docker.docker_image:
    name: "{{ backend_image_name }}"
    source: build
    
    build:
      path: "{{ backend_app_dir }}"
      args:
        JAR_FILE: "target/fuelman-1.0.0.jar"
- name: Run backend container
  community.docker.docker_container:
    name: "{{ backend_container_name }}"
    image: "{{ backend_image_name }}"

    state: started
    restart_policy: always
    recreate: true

    networks:
      - name: "{{ backend_network }}"

    ports:
      - "{{ backend_host_port }}:8080"

    env:
      TZ: Asia/Kolkata

      JAVA_OPTS: "{{ backend_java_opts }}" 
