---
- name: Reload PostgreSQL
  command:
    argv:
      - docker
      - exec
      - -e
      - "PGPASSWORD={{ postgres_password }}"
      - "{{ postgres_container_name }}"
      - psql
      - -h
      - "127.0.0.1"
      - -U
      - "{{ postgres_user }}"
      - -d
      - "{{ postgres_db }}"
      - -c
      - "SELECT pg_reload_conf();"
