# backend_branch: main
# backend_network: prod
# backend_container_port: 8080
# are common to all backend applications and no need to give specific with applications level


backend_name: "fuelman-api"

backend_repo: "git@github.com:maargali/fuelman.git"


backend_container_name: fuelmanAppProd
backend_image_name:  "fuelman-app"

backend_host_port: 8080

app_name: fuelman
app_jar_file: "target/{{ app_name }}-1.0.0.jar"

backend_schema: fman

backend_java_opts: >-
  -Dspring.profiles.active=prod
  -Dlogging.level.root=INFO
  -Dfleet.endpoint.url=https://your-api-url
  -Dapp.database.url=jdbc:postgresql://{{ postgres_container_name }}:{{ postgres_port }}/{{ postgres_db }}?currentSchema={{ backend_schema }}&options=-ctimezone=Asia/Kolkata
  -Dapp.database.user={{ postgres_user }}
  -Dapp.database.pass={{ postgres_password }}
  -Duser.timezone=Asia/Kolkata
