- name: Stop existing container
  community.docker.docker_container:
    name: "{{ postgres_container_name }}"
    state: absent
    force_kill: true

- name: Remove postgres bind mount data
  file:
    path: "{{ postgres_data_dir }}"
    state: absent

- name: Recreate clean directory
  file:
    path: "{{ postgres_data_dir }}"
    state: directory
    owner: 999
    group: 999
    mode: "0755"

- name: Remove unused docker volumes
  command: docker volume prune -f
  changed_when: false
