- hosts: prod
  become: true

  vars_files:
    - ../inventory/prod/group_vars/backend/fleet-api.yml

  vars:
    build_name: fleet-prod
    env: prod
 
  roles:
    - docker
    - backend

  tasks:
    - name: Deployment Summary
      debug:
         msg: 
          - "======================================"
          - "Deployment Completed"
          - "Application : {{ build_name }}"
          - "Environment : {{ env }}"
          - "Server      : {{ ansible_host }}"
          - "======================================"
