certbot_domains:
  - fuelman.shop
  - www.fuelman.shop
    # enable below domains after adding dns mapping in hostinger or where ever is required
    # - anchor.fuelman.shop
    #  - fleet.fuelman.shop

certbot_email: maargali.company@gmail.com
