nginx_vhosts:

  - name: fuelman

    server_names:
      - fuelman.in
      - www.fuelman.in

    primary_domain: fuelman.in
    cert_name: fuelman.in

    nginx_locations:
      - path: /
        proxy_pass: http://fuelman-ui-prod:80

      - path: /api
        proxy_pass: http://fuelmanAppProd:8080

  
  - name: fleet

    server_names:
      - fleet.fuelman.in

    primary_domain: fleet.fuelman.in
    cert_name: fuelman.in

    nginx_locations:
      - path: /
        proxy_pass: http://fleet-ui-prod:80

          #  - name: anchor

          # server_names:
          # - anchor.fuelman.in

          #primary_domain: anchor.fuelman.in

          #nginx_locations:
          #- path: /
          # proxy_pass: http://anchor-ui-prod:80

          # - path: /api
          #  proxy_pass: http://anchor-app-prod:9080
