# ===== Stage 1: Build React App =====

FROM node:18-alpine AS builder

WORKDIR /app

# Build arguments

ARG APP_ENV
ARG REACT_APP_API_URL
ARG REACT_APP_FLEET_REDIRECT_URL

# Export as environment variables for React build

ENV APP_ENV=$APP_ENV
ENV REACT_APP_API_URL=$REACT_APP_API_URL
ENV REACT_APP_FLEET_REDIRECT_URL=$REACT_APP_FLEET_REDIRECT_URL

COPY package*.json ./

RUN npm ci --legacy-peer-deps

COPY . .

ENV GENERATE_SOURCEMAP=false

RUN npm run build

# ===== Stage 2: Nginx =====

FROM nginx:alpine

WORKDIR /usr/share/nginx/html

COPY --from=builder /app/build .

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

